version: '3.9'
services:
  api:
    build:
      context: ../
      dockerfile: api-gateway/Dockerfile
    image: tat-platform-backend:api-gateway
    networks:
      - tat-platform
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/project/app

networks:
  tat-platform:
    external: true
