"""update patient table

Revision ID: 5678320a0b44
Revises: 7225ad4c5752
Create Date: 2024-04-07 11:43:52.166072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5678320a0b44"
down_revision: Union[str, None] = "7225ad4c5752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patient",
        "snils",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "patient",
        "contacts",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "patient",
        "contacts",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "patient",
        "snils",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
