"""add workers & positions tables

Revision ID: 7225ad4c5752
Revises: e695a629cf71
Create Date: 2024-04-07 10:12:04.510683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7225ad4c5752"
down_revision: Union[str, None] = "e695a629cf71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snils", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("date_begin", sa.Date(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("contacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "position",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date_begin", sa.Date(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("department_name", sa.String(), nullable=False),
        sa.Column("position_name", sa.String(), nullable=False),
        sa.Column("position_rate", sa.String(), nullable=True),
        sa.Column("position_fed_code", sa.String(), nullable=False),
        sa.Column("position_reg_name", sa.String(), nullable=True),
        sa.Column("position_speciality_code", sa.String(), nullable=True),
        sa.Column("position_speciality_name", sa.String(), nullable=True),
        sa.Column("worker_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"]),
        sa.ForeignKeyConstraint(["worker_id"], ["worker.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position")
    op.drop_table("worker")
    # ### end Alembic commands ###
